// Russian glossary for Claude Code's console phrases. Applied to the terminal stream on the
// phone (the PC sees the original), so menus like "Do you want to proceed?" read in Russian.
// Order matters: longer phrases first. Only exact English fragments are touched, so paths,
// code and command output stay as they are.
window.CC_RU = [
  ["Yes, and don't ask again for similar commands in", "Да, и больше не спрашивать для похожих команд в"],
  ["Yes, and don't ask again for", "Да, и больше не спрашивать для"],
  ["Yes, allow all edits during this session", "Да, разрешить все правки в этой сессии"],
  ["Yes, and don't ask again this session", "Да, и больше не спрашивать в этой сессии"],
  ["Yes, and auto-accept edits", "Да, и дальше принимать правки автоматически"],
  ["No, and tell Claude what to do differently", "Нет, и сказать Claude, что сделать иначе"],
  ["No, keep planning", "Нет, продолжить планирование"],
  ["Do you want to make this edit to", "Внести эту правку в"],
  ["Do you want to create", "Создать файл"],
  ["Do you want to proceed?", "Продолжить?"],
  ["Do you want to run this command?", "Выполнить эту команду?"],
  ["Do you want to", "Хотите"],
  ["Would you like to proceed?", "Продолжить?"],
  ["Would you like to", "Хотите"],
  ["Press Ctrl-C again to exit", "Нажмите Ctrl+C ещё раз для выхода"],
  ["Press Enter to continue", "Нажмите Enter, чтобы продолжить"],
  ["Press up to edit queued messages", "Стрелка вверх — изменить сообщения в очереди"],
  ["Esc to cancel", "Esc — отмена"],
  ["Enter to confirm", "Enter — подтвердить"],
  ["Enter to select", "Enter — выбрать"],
  ["Enter to send", "Enter — отправить"],
  ["↑/↓ to select", "↑/↓ — выбор"],
  ["Use arrow keys to navigate", "Стрелки — перемещение"],
  ["Tab to toggle", "Tab — переключить"],
  ["? for shortcuts", "? — горячие клавиши"],
  ["Type your message", "Введите сообщение"],
  ["Try \"", "Попробуйте \""],
  ["Welcome to Claude Code!", "Добро пожаловать в Claude Code!"],
  ["Welcome back", "С возвращением"],
  ["Tips for getting started", "С чего начать"],
  ["What would you like to do?", "Что сделать?"],
  ["Let me know how I can help", "Скажите, чем помочь"],
  ["Context left until auto-compact", "Контекста до автосжатия"],
  ["Context low", "Контекст заканчивается"],
  ["Compacting conversation", "Сжимаю историю"],
  ["Conversation compacted", "История сжата"],
  ["Auto-compacting", "Автосжатие"],
  ["Thinking…", "Думаю…"], ["Thinking...", "Думаю…"],
  ["Accomplishing…", "Выполняю…"], ["Working…", "Работаю…"], ["Brewing…", "Готовлю…"], ["Pondering…", "Размышляю…"],
  ["Reading file", "Читаю файл"], ["Editing file", "Правлю файл"], ["Writing file", "Пишу файл"], ["Creating file", "Создаю файл"],
  ["Searching for", "Ищу"], ["Searching files", "Ищу по файлам"], ["Running command", "Выполняю команду"], ["Running tests", "Запускаю тесты"],
  ["Bash command", "Команда Bash"], ["Edit file", "Правка файла"], ["Write file", "Запись файла"], ["Read file", "Чтение файла"],
  ["Create file", "Создание файла"], ["Delete file", "Удаление файла"], ["Fetch URL", "Загрузка страницы"], ["Web search", "Поиск в интернете"],
  ["Permission required", "Нужно разрешение"], ["Permission denied", "Отказано"], ["Allow once", "Разрешить один раз"], ["Allow always", "Разрешить всегда"],
  ["Allow", "Разрешить"], ["Deny", "Запретить"],
  ["accept edits on", "авто-принятие правок вкл."], ["accept edits off", "авто-принятие правок выкл."],
  ["auto-accept edits on", "авто-принятие правок вкл."], ["auto-accept edits off", "авто-принятие правок выкл."],
  ["plan mode on", "режим плана вкл."], ["plan mode off", "режим плана выкл."], ["Plan mode", "Режим плана"],
  ["Bypassing Permissions", "Без запросов разрешений"], ["bypass permissions on", "без запросов разрешений"],
  ["shift+tab to cycle", "shift+tab — сменить режим"],
  ["Remote Control enabled", "Remote Control включён"], ["Remote Control is on", "Remote Control включён"],
  ["Remote Control disabled", "Remote Control выключен"],
  ["This session is now available in the Claude app", "Эта сессия доступна в приложении Claude"],
  ["Update available", "Доступно обновление"], ["Updating…", "Обновляю…"], ["Update installed", "Обновление установлено"],
  ["Restart to apply", "Перезапустите, чтобы применить"],
  ["Logged in as", "Вход выполнен как"], ["Not logged in", "Вход не выполнен"], ["Login successful", "Вход выполнен"],
  ["Session resumed", "Сессия восстановлена"], ["Resume session", "Продолжить сессию"], ["No conversations found", "Бесед не найдено"],
  ["Total cost", "Стоимость"], ["Total duration", "Длительность"], ["Total code changes", "Изменений кода"],
  ["Usage by model", "Расход по моделям"], ["input tokens", "входных токенов"], ["output tokens", "выходных токенов"],
  ["Interrupted by user", "Прервано пользователем"], ["Interrupted", "Прервано"], ["Cancelled", "Отменено"],
  ["Waiting for user input", "Жду ответа"], ["Waiting for permission", "Жду разрешения"],
  ["Tool use rejected", "Действие отклонено"], ["Task completed", "Задача выполнена"], ["Task failed", "Задача не выполнена"],
  ["Error:", "Ошибка:"], ["Warning:", "Внимание:"], ["Failed to", "Не удалось"], ["Rate limit", "Лимит запросов"],
  ["Network error", "Ошибка сети"], ["Connection lost", "Связь потеряна"], ["Reconnecting", "Переподключаюсь"],
  ["Select an option", "Выберите вариант"], ["Select a model", "Выберите модель"], ["Choose", "Выберите"],
  ["Are you sure?", "Вы уверены?"], ["(recommended)", "(рекомендуется)"], ["(default)", "(по умолчанию)"],
  ["Yes", "Да"], ["No", "Нет"],
];
